version: "3.7"

services:

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass sOmE_sEcUrE_pAsS
        ports:
            - "6379:6379"
        environment:
            - REDIS_REPLICATION_MODE=master

    mong:
        image: mongo:4.2
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
        ports:
            - "27017:27017"
        

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02
            - cluster.initial_master_nodes=elasticsearch,es02
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
       
    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        container_name: es02
        environment:
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_master_nodes=elasticsearch,es02
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1        
    
    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.3
        ports:
            - "5601:5601"


    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "MySql2019!"
            MYSQL_DATABASE: "testedb"
        ports:
            - "3306:3306"
        