FROM node:14-alpine AS BUILD_IMAGE

RUN apk update && apk add yarn curl bash

WORKDIR /usr/src/app

COPY package*.json ./

RUN curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin

RUN yarn install --production=true

COPY . .

RUN yarn tsc

FROM node:14-alpine

COPY --from=BUILD_IMAGE /usr/src/app/dist ./dist
COPY --from=BUILD_IMAGE /usr/src/app/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "dist/src/http/app/Server.js"]