version: "3.7"

services:

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass sOmE_sEcUrE_pAsS
        ports:
            - "6379:6379"
        volumes:
            - $PWD/redis-data:/var/lib/redis
            - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master

    mong:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
        ports:
            - "27017:27017"
        volumes:
            - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        
        ports:
            - 9200:9200

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "MySql2019!"
            MYSQL_DATABASE: "testedb"
        ports:
            - "3306:3306"
        